# Generated by Django 5.2.5 on 2025-08-24 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_theme', models.CharField(default='ocean_blue', max_length=20, verbose_name='Chat Theme')),
                ('show_timestamps', models.BooleanField(default=True, verbose_name='Show Timestamps')),
                ('enable_sound_notifications', models.BooleanField(default=True, verbose_name='Enable Sound Notifications')),
                ('preferred_response_style', models.CharField(default='balanced', max_length=20, verbose_name='Preferred Response Style')),
                ('enable_proactive_suggestions', models.BooleanField(default=True, verbose_name='Enable Proactive Suggestions')),
                ('allow_conversation_analysis', models.BooleanField(default=True, verbose_name='Allow Conversation Analysis')),
                ('share_data_for_improvements', models.BooleanField(default=True, verbose_name='Share Data for Improvements')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('support', 'Support Agent')], default='customer', max_length=10, verbose_name='Role')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Display Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('preferred_language', models.CharField(default='en', max_length=10, verbose_name='Preferred Language')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='Total Conversations')),
                ('total_messages_sent', models.IntegerField(default=0, verbose_name='Total Messages Sent')),
                ('average_satisfaction', models.FloatField(default=0.0, verbose_name='Average Satisfaction')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Last Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Last Active')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='Device Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total Requests')),
                ('last_activity_type', models.CharField(blank=True, max_length=50, verbose_name='Last Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('chat', 'Chat Message'), ('view', 'Page View'), ('api', 'API Call'), ('upload', 'File Upload'), ('download', 'File Download'), ('admin', 'Admin Action'), ('logout', 'Logout')], max_length=20, verbose_name='Activity Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='authentication.usersession')),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_active'], name='authenticat_user_id_bf91bd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', '-last_active'], name='authenticat_is_acti_cb20a9_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', '-timestamp'], name='authenticat_session_820e34_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['activity_type', '-timestamp'], name='authenticat_activit_cd3be2_idx'),
        ),
    ]
