# Generated by Django 5.2.4 on 2025-08-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'verbose_name': 'User Preferences', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='allow_conversation_analysis',
            field=models.BooleanField(default=True, verbose_name='Allow Conversation Analysis'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='chat_theme',
            field=models.CharField(default='ocean_blue', max_length=20, verbose_name='Chat Theme'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='enable_proactive_suggestions',
            field=models.BooleanField(default=True, verbose_name='Enable Proactive Suggestions'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='enable_sound_notifications',
            field=models.BooleanField(default=True, verbose_name='Enable Sound Notifications'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_response_style',
            field=models.CharField(default='balanced', max_length=20, verbose_name='Preferred Response Style'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='share_data_for_improvements',
            field=models.BooleanField(default=True, verbose_name='Share Data for Improvements'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='show_timestamps',
            field=models.BooleanField(default=True, verbose_name='Show Timestamps'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='average_satisfaction',
            field=models.FloatField(default=0.0, verbose_name='Average Satisfaction'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email Notifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('support', 'Support Agent')], default='customer', max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_conversations',
            field=models.IntegerField(default=0, verbose_name='Total Conversations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_messages_sent',
            field=models.IntegerField(default=0, verbose_name='Total Messages Sent'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
