# Generated by Django 5.2.4 on 2025-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userpreferences_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Display Name'),
        ),
    ]
