# Generated by Django 5.2.5 on 2025-08-24 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude')], max_length=20, unique=True, verbose_name='Provider')),
                ('api_key', models.TextField(help_text='API key for the provider', verbose_name='API Key')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('llm_analysis', models.TextField(default='', verbose_name='LLM Analysis')),
                ('analysis_period', models.CharField(default='Unknown', help_text='Time period covered by this analysis (e.g., "Last 24 hours", "Today", "This week")', max_length=50, verbose_name='Analysis Period')),
                ('messages_analyzed_count', models.IntegerField(default=0, verbose_name='Messages Analyzed')),
                ('critical_issues_found', models.IntegerField(default=0, verbose_name='Critical Issues Found')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('trigger_reason', models.CharField(default='legacy_migration', help_text='What triggered this automatic summary generation', max_length=100, verbose_name='Generation Trigger')),
                ('llm_model_used', models.CharField(blank=True, max_length=50, verbose_name='LLM Model Used')),
                ('llm_response_time', models.FloatField(blank=True, null=True, verbose_name='LLM Response Time')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Prompt Name')),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('greeting', 'Greeting Prompt'), ('error', 'Error Handling'), ('clarification', 'Clarification Request'), ('escalation', 'Escalation Prompt'), ('closing', 'Conversation Closing'), ('instruction', 'Instruction Prompt'), ('custom', 'Custom Prompt')], max_length=20, verbose_name='Prompt Type')),
                ('prompt_text', models.TextField(help_text='The actual prompt text that will be sent to the LLM', verbose_name='Prompt Text')),
                ('description', models.TextField(blank=True, help_text='Description of when and how this prompt is used', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default prompt for this type', verbose_name='Is Default')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='Language')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Admin Prompt',
                'verbose_name_plural': 'Admin Prompts',
                'ordering': ['prompt_type', 'language', '-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total Messages')),
                ('satisfaction_score', models.FloatField(blank=True, null=True, verbose_name='Satisfaction Score')),
                ('langextract_analysis', models.JSONField(blank=True, default=dict, verbose_name='LangExtract Analysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('content', models.TextField(verbose_name='Content')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('admin', 'Admin')], max_length=10, verbose_name='Sender Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('feedback', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True, verbose_name='Feedback')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/', verbose_name='File Attachment')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Response Time')),
                ('llm_model_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='LLM Model Used')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='Tokens Used')),
                ('message_analysis', models.JSONField(blank=True, default=dict, verbose_name='Message Analysis')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Session ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer Session',
                'verbose_name_plural': 'Customer Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
