# Generated by Django 5.2.4 on 2025-08-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Test Model',
                'verbose_name_plural': 'Test Models',
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-started_at'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='langextract_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='LangExtract Analysis'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='satisfaction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Satisfaction Score'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='total_messages',
            field=models.IntegerField(default=0, verbose_name='Total Messages'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/', verbose_name='File Attachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='llm_model_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LLM Model Used'),
        ),
        migrations.AlterField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='message',
            name='response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Response Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('admin', 'Admin')], max_length=10, verbose_name='Sender Type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended At'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='total_conversations',
            field=models.IntegerField(default=0, verbose_name='Total Conversations'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='total_messages_sent',
            field=models.IntegerField(default=0, verbose_name='Total Messages Sent'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
