# Generated by Django 5.2.4 on 2025-08-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_testmodel_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude')], max_length=20, unique=True, verbose_name='Provider')),
                ('api_key', models.TextField(help_text='API key for the provider', verbose_name='API Key')),
                ('model_name', models.CharField(default='gpt-3.5-turbo', help_text='Default model to use for this provider', max_length=100, verbose_name='Model Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'ordering': ['provider'],
            },
        ),
    ]
