# Generated by Django 5.2.4 on 2025-08-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_apiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='model_name',
            field=models.CharField(default='gpt-3.5-turbo', help_text='Input Model Name', max_length=100, verbose_name='Model Name'),
        ),
    ]
