# Generated by Django 5.2.4 on 2025-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_apiconfiguration_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='model_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100, verbose_name='Model Name'),
        ),
    ]
