# Generated by Django 5.2.4 on 2025-08-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_apiconfiguration_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Model Name'),
        ),
    ]
