# Generated by Django 5.2.4 on 2025-08-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_apiconfiguration_model_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
