# Generated by Django 5.2.4 on 2025-08-07 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_testmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Prompt Name')),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('greeting', 'Greeting Prompt'), ('error', 'Error Handling'), ('clarification', 'Clarification Request'), ('escalation', 'Escalation Prompt'), ('closing', 'Conversation Closing'), ('instruction', 'Instruction Prompt'), ('custom', 'Custom Prompt')], max_length=20, verbose_name='Prompt Type')),
                ('prompt_text', models.TextField(help_text='The actual prompt text that will be sent to the LLM', verbose_name='Prompt Text')),
                ('description', models.TextField(blank=True, help_text='Description of when and how this prompt is used', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default prompt for this type', verbose_name='Is Default')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], default='en', max_length=10, verbose_name='Language')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Admin Prompt',
                'verbose_name_plural': 'Admin Prompts',
                'ordering': ['prompt_type', 'language', '-is_default', 'name'],
            },
        ),
    ]
