# Generated by Django 5.2.4 on 2025-08-11 05:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_referencedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_used',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tokens Used'),
        ),
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
    ]
