# Generated by Django 5.2.4 on 2025-08-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_conversationinsight_learningpattern_unknownissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpattern',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='learningpattern',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='learningpattern',
            name='source_conversations',
        ),
        migrations.RemoveField(
            model_name='unknownissue',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='unknownissue',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='ConversationInsight',
        ),
        migrations.DeleteModel(
            name='LearningPattern',
        ),
        migrations.DeleteModel(
            name='UnknownIssue',
        ),
    ]
