# Generated by Django 5.2.4 on 2025-08-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_learningpattern_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='Message Analysis'),
        ),
    ]
