# Generated by Django 5.2.4 on 2025-08-17 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_message_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=200, verbose_name='Summary Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_from', models.DateTimeField(verbose_name='Analysis From Date')),
                ('date_to', models.DateTimeField(verbose_name='Analysis To Date')),
                ('min_importance_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Minimum Importance Level')),
                ('total_conversations_analyzed', models.IntegerField(default=0, verbose_name='Total Conversations Analyzed')),
                ('total_messages_analyzed', models.IntegerField(default=0, verbose_name='Total Messages Analyzed')),
                ('meaningful_messages_count', models.IntegerField(default=0, verbose_name='Meaningful Messages Count')),
                ('important_topics', models.JSONField(default=list, verbose_name='Important Topics')),
                ('faq_gaps', models.JSONField(default=list, verbose_name='FAQ Gaps')),
                ('doc_improvement_suggestions', models.JSONField(default=list, verbose_name='Documentation Improvement Suggestions')),
                ('user_satisfaction_trends', models.JSONField(default=dict, verbose_name='User Satisfaction Trends')),
                ('bot_performance_metrics', models.JSONField(default=dict, verbose_name='Bot Performance Metrics')),
                ('topic_frequency_analysis', models.JSONField(default=dict, verbose_name='Topic Frequency Analysis')),
                ('urgency_distribution', models.JSONField(default=dict, verbose_name='Urgency Distribution')),
                ('question_types_analysis', models.JSONField(default=dict, verbose_name='Question Types Analysis')),
                ('escalation_patterns', models.JSONField(default=dict, verbose_name='Escalation Patterns')),
                ('executive_summary', models.TextField(blank=True, verbose_name='Executive Summary')),
                ('key_recommendations', models.TextField(blank=True, verbose_name='Key Recommendations')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('analysis_config', models.JSONField(default=dict, verbose_name='Analysis Configuration')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Conversation Summary',
                'verbose_name_plural': 'Conversation Summaries',
                'ordering': ['-generated_at'],
            },
        ),
    ]
