# Generated by Django 5.2.4 on 2025-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_add_conversation_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationsummary',
            name='analysis_config',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='bot_performance_metrics',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='doc_improvement_suggestions',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='escalation_patterns',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='executive_summary',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='faq_gaps',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='important_topics',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='key_recommendations',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='meaningful_messages_count',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='min_importance_level',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='question_types_analysis',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='topic_frequency_analysis',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='total_conversations_analyzed',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='total_messages_analyzed',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='urgency_distribution',
        ),
        migrations.RemoveField(
            model_name='conversationsummary',
            name='user_satisfaction_trends',
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='analysis_period',
            field=models.CharField(default='Unknown', help_text='Time period covered by this analysis (e.g., "Last 24 hours", "Today", "This week")', max_length=50, verbose_name='Analysis Period'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='critical_issues_found',
            field=models.IntegerField(default=0, verbose_name='Critical Issues Found'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='llm_analysis',
            field=models.TextField(default='', verbose_name='LLM Analysis'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='llm_model_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='LLM Model Used'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='llm_response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='LLM Response Time'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='messages_analyzed_count',
            field=models.IntegerField(default=0, verbose_name='Messages Analyzed'),
        ),
        migrations.AddField(
            model_name='conversationsummary',
            name='trigger_reason',
            field=models.CharField(default='legacy_migration', help_text='What triggered this automatic summary generation', max_length=100, verbose_name='Generation Trigger'),
        ),
    ]
