# Generated by Django 5.2.4 on 2025-08-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_redesign_conversation_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationsummary',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Summary', 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Customer Session', 'verbose_name_plural': 'Customer Sessions'},
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='total_conversations',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='total_messages_sent',
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Activity'),
        ),
    ]
