# Generated by Django 5.2.4 on 2025-08-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('average_satisfaction', models.FloatField(default=0.0)),
                ('positive_conversations', models.IntegerField(default=0)),
                ('negative_conversations', models.IntegerField(default=0)),
                ('neutral_conversations', models.IntegerField(default=0)),
                ('total_issues_raised', models.IntegerField(default=0)),
                ('resolved_issues', models.IntegerField(default=0)),
                ('escalated_issues', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('bot_vs_human_ratio', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('satisfaction_level', models.IntegerField()),
                ('issues_raised', models.JSONField(default=list)),
                ('urgency_indicators', models.JSONField(default=list)),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('escalated', 'Escalated')], max_length=10)),
                ('customer_intent', models.CharField(max_length=50)),
                ('key_insights', models.JSONField(default=list)),
                ('source_spans', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('langextract_model_used', models.CharField(max_length=50)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='chat.conversation')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenced_at', models.DateTimeField(auto_now_add=True)),
                ('effectiveness_score', models.FloatField(blank=True, null=True)),
                ('search_query', models.CharField(max_length=200)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='documents.companydocument')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
            options={
                'ordering': ['-referenced_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
