# Generated by Django 5.2.4 on 2025-08-07 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('chat', '0004_alter_apiconfiguration_model_name'),
        ('documents', '0002_alter_companydocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticssummary',
            options={'ordering': ['-date'], 'verbose_name': 'Analytics Summary', 'verbose_name_plural': 'Analytics Summaries'},
        ),
        migrations.AlterModelOptions(
            name='conversationanalysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analysis'},
        ),
        migrations.AlterModelOptions(
            name='documentusage',
            options={'ordering': ['-referenced_at'], 'verbose_name': 'Document Usage', 'verbose_name_plural': 'Document Usage'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedback'},
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='average_response_time',
            field=models.FloatField(default=0.0, verbose_name='Average Response Time'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='average_satisfaction',
            field=models.FloatField(default=0.0, verbose_name='Average Satisfaction'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='bot_vs_human_ratio',
            field=models.FloatField(default=0.0, verbose_name='Bot vs Human Ratio'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='escalated_issues',
            field=models.IntegerField(default=0, verbose_name='Escalated Issues'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='negative_conversations',
            field=models.IntegerField(default=0, verbose_name='Negative Conversations'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='neutral_conversations',
            field=models.IntegerField(default=0, verbose_name='Neutral Conversations'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='positive_conversations',
            field=models.IntegerField(default=0, verbose_name='Positive Conversations'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='resolved_issues',
            field=models.IntegerField(default=0, verbose_name='Resolved Issues'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='total_conversations',
            field=models.IntegerField(default=0, verbose_name='Total Conversations'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='total_issues_raised',
            field=models.IntegerField(default=0, verbose_name='Total Issues Raised'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='total_messages',
            field=models.IntegerField(default=0, verbose_name='Total Messages'),
        ),
        migrations.AlterField(
            model_name='analyticssummary',
            name='unique_users',
            field=models.IntegerField(default=0, verbose_name='Unique Users'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Analyzed At'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='confidence_score',
            field=models.FloatField(default=0.0, verbose_name='Confidence Score'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='chat.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='customer_intent',
            field=models.CharField(max_length=50, verbose_name='Customer Intent'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='issues_raised',
            field=models.JSONField(default=list, verbose_name='Issues Raised'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='key_insights',
            field=models.JSONField(default=list, verbose_name='Key Insights'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='langextract_model_used',
            field=models.CharField(max_length=50, verbose_name='LangExtract Model Used'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing Time'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='resolution_status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('escalated', 'Escalated')], max_length=10, verbose_name='Resolution Status'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='satisfaction_level',
            field=models.IntegerField(verbose_name='Satisfaction Level'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10, verbose_name='Sentiment'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='source_spans',
            field=models.JSONField(default=list, verbose_name='Source Spans'),
        ),
        migrations.AlterField(
            model_name='conversationanalysis',
            name='urgency_indicators',
            field=models.JSONField(default=list, verbose_name='Urgency Indicators'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='documents.companydocument', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='effectiveness_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Effectiveness Score'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='referenced_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Referenced At'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='search_query',
            field=models.CharField(max_length=200, verbose_name='Search Query'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, verbose_name='Feedback Type'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='chat.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
