# Generated by Django 5.2.4 on 2025-08-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_update_documentusage_to_new_document'),
        ('chat', '0014_message_message_analysis'),
        ('documents', '0011_enhance_document_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentusage',
            name='context_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Context Category'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='excerpt_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Excerpt Length'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='excerpt_start_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Position'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='excerpt_used',
            field=models.TextField(blank=True, verbose_name='Excerpt Used'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='keywords_matched',
            field=models.JSONField(default=list, verbose_name='Keywords Matched'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='llm_model_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='LLM Model Used'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing Time'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='relevance_score',
            field=models.FloatField(default=0.0, verbose_name='Relevance Score'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='response_helpful',
            field=models.BooleanField(blank=True, null=True, verbose_name='Response Helpful'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='usage_type',
            field=models.CharField(choices=[('full_context', 'Full Context'), ('excerpt', 'Excerpt'), ('summary', 'Summary'), ('keyword_match', 'Keyword Match')], default='excerpt', max_length=20, verbose_name='Usage Type'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True, verbose_name='User Feedback'),
        ),
        migrations.AddField(
            model_name='documentusage',
            name='user_intent',
            field=models.CharField(blank=True, max_length=100, verbose_name='User Intent'),
        ),
        migrations.AlterField(
            model_name='documentusage',
            name='search_query',
            field=models.CharField(max_length=500, verbose_name='Search Query'),
        ),
        migrations.AddIndex(
            model_name='documentusage',
            index=models.Index(fields=['document', '-referenced_at'], name='analytics_d_documen_f2db59_idx'),
        ),
        migrations.AddIndex(
            model_name='documentusage',
            index=models.Index(fields=['search_query'], name='analytics_d_search__0aaf88_idx'),
        ),
        migrations.AddIndex(
            model_name='documentusage',
            index=models.Index(fields=['relevance_score'], name='analytics_d_relevan_c9dee7_idx'),
        ),
    ]
