# Generated by Django 5.2.4 on 2025-08-07 05:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_apiconfiguration_model_name'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company Document', 'verbose_name_plural': 'Company Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Document Category', 'verbose_name_plural': 'Document Categories'},
        ),
        migrations.AlterModelOptions(
            name='documentfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document Feedback', 'verbose_name_plural': 'Document Feedback'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document Version', 'verbose_name_plural': 'Document Versions'},
        ),
        migrations.AlterModelOptions(
            name='knowledgegap',
            options={'ordering': ['-frequency', '-last_encountered'], 'verbose_name': 'Knowledge Gap', 'verbose_name_plural': 'Knowledge Gaps'},
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='content_summary',
            field=models.TextField(blank=True, verbose_name='Content Summary'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='effectiveness_score',
            field=models.FloatField(default=0.0, verbose_name='Effectiveness Score'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to='company_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'md'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='keywords',
            field=models.JSONField(default=list, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='last_referenced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Referenced'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Usage Count'),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='color',
            field=models.CharField(default='#0288D1', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='documents.companydocument', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('outdated', 'Outdated'), ('unclear', 'Unclear')], max_length=15, verbose_name='Feedback Type'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='search_query',
            field=models.CharField(blank=True, max_length=200, verbose_name='Search Query'),
        ),
        migrations.AlterField(
            model_name='documentfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='change_notes',
            field=models.TextField(blank=True, verbose_name='Change Notes'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='Content Text'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.companydocument', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='document_versions/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.CharField(max_length=20, verbose_name='Version Number'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='first_identified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='First Identified'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='last_encountered',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Encountered'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='query',
            field=models.CharField(max_length=500, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Resolution Notes'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
        migrations.AlterField(
            model_name='knowledgegap',
            name='status',
            field=models.CharField(choices=[('identified', 'Identified'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='identified', max_length=15, verbose_name='Status'),
        ),
    ]
