# Generated by Django 5.2.4 on 2025-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_add_uuid_and_file_hash'),
    ]

    operations = [
        # Add knowledge base fields to existing Document model
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Full text extracted from document for knowledge base', verbose_name='Extracted Text'),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of document content', verbose_name='AI Summary'),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_keywords_json',
            field=models.TextField(blank=True, default='[]', help_text='AI-extracted keywords and topics (JSON string)', verbose_name='AI Keywords JSON'),
        ),
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=models.TextField(blank=True, db_index=True, help_text='Preprocessed text for fast searching', verbose_name='Search Vector'),
        ),
        migrations.AddField(
            model_name='document',
            name='reference_count',
            field=models.IntegerField(default=0, help_text='Number of times referenced by LLM', verbose_name='Reference Count'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_referenced',
            field=models.DateTimeField(blank=True, help_text='Last time this document was used by LLM', null=True, verbose_name='Last Referenced'),
        ),
        migrations.AddField(
            model_name='document',
            name='effectiveness_score',
            field=models.FloatField(default=0.0, help_text='How useful this document is for answering questions', verbose_name='Effectiveness Score'),
        ),
    ]