# Generated by Django 5.2.4 on 2025-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_knowledge_base_fields_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='document',
        ),
        migrations.RemoveField(
            model_name='knowledgegap',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='documentfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentfeedback',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='documentfeedback',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documentprocessingqueue',
            name='document',
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='knowledgegap',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='knowledgegap',
            name='conversations',
        ),
        migrations.RemoveField(
            model_name='smartdocument',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='SHA-256 hash for duplicate detection', max_length=64, verbose_name='File Hash'),
        ),
        migrations.DeleteModel(
            name='AIDocHelperLog',
        ),
        migrations.DeleteModel(
            name='CompanyDocument',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='DocumentFeedback',
        ),
        migrations.DeleteModel(
            name='DocumentProcessingQueue',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
        migrations.DeleteModel(
            name='KnowledgeGap',
        ),
        migrations.DeleteModel(
            name='SmartDocument',
        ),
    ]
