# Generated by Django 5.2.4 on 2025-08-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_companydocument_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunks_count',
            field=models.IntegerField(default=0, help_text='Number of text chunks generated', verbose_name='Chunks Count'),
        ),
        migrations.AddField(
            model_name='document',
            name='chunks_json',
            field=models.TextField(blank=True, default='[]', help_text='Text chunks for vector embeddings (JSON array)', verbose_name='Document Chunks JSON'),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Name of the embedding model used', max_length=100, verbose_name='Embedding Model'),
        ),
        migrations.AddField(
            model_name='document',
            name='embeddings_generated',
            field=models.BooleanField(default=False, help_text='Whether vector embeddings have been generated for this document', verbose_name='Embeddings Generated'),
        ),
    ]
