# Generated by Django 5.2.4 on 2025-08-15 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_message_analysis'),
        ('documents', '0009_document_chunks_count_document_chunks_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('conversation_title', models.CharField(blank=True, help_text='Display title for the conversation', max_length=255, verbose_name='Conversation Title')),
                ('issues_detected', models.TextField(blank=True, help_text='Specific issues like account, password, pricing concerns', verbose_name='Issues Detected')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('langextract_analysis_summary', models.TextField(blank=True, help_text='User-friendly summary of conversation analysis', verbose_name='LangExtract Analysis Summary')),
                ('langextract_full_analysis', models.JSONField(blank=True, default=dict, help_text='Complete analysis data from LangExtract', verbose_name='Full LangExtract Analysis')),
                ('category', models.CharField(blank=True, help_text='Category based on LangExtract analysis', max_length=100, verbose_name='Category')),
                ('satisfaction_level', models.IntegerField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], help_text='Customer satisfaction rating from 1-5', null=True, verbose_name='Satisfaction Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('analysis_completed', models.BooleanField(default=False, help_text='Whether LangExtract analysis has been completed', verbose_name='Analysis Completed')),
                ('analysis_error', models.TextField(blank=True, help_text='Error message if analysis failed', verbose_name='Analysis Error')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_improvements', to='chat.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Documentation Improvement',
                'verbose_name_plural': 'Documentation Improvements',
                'ordering': ['-created_at'],
            },
        ),
    ]
