# Generated by Django 5.2.4 on 2025-08-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20250815_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationimprovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doc Improvement', 'verbose_name_plural': 'Doc Improvements'},
        ),
    ]
