# Generated by Django 5.2.4 on 2025-08-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHelperKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('documents', 'Document Management'), ('users', 'User Management'), ('chat', 'Chat System'), ('analytics', 'Analytics'), ('system', 'System Information'), ('api', 'API Information'), ('general', 'General Help')], max_length=20, verbose_name='Category')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('question_patterns', models.TextField(help_text='Common questions or keywords that trigger this response', verbose_name='Question Patterns')),
                ('response_template', models.TextField(help_text='Template response for this topic', verbose_name='Response Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AI Helper Knowledge',
                'verbose_name_plural': 'AI Helper Knowledge Base',
                'ordering': ['category', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='AIHelperChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Session ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Chat Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Helper Chat',
                'verbose_name_plural': 'AI Helper Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIHelperMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=10, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data used for AI response', verbose_name='Context Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_helper.aihelperchat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'AI Helper Message',
                'verbose_name_plural': 'AI Helper Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
